import type { Condominio, Morador, Funcionario, EmpresaTerceirizada, Fornecedor, Veiculo, Visitante, Reserva, Ocorrencia, Usuario } from '../types';

export const mockCondominio: Condominio = {
  id: '1',
  nome: 'Residencial Jardim das Flores',
  nomeFantasia: 'Jardim das Flores',
  cnpj: '12.345.678/0001-90',
  endereco: {
    logradouro: 'Rua das Flores',
    numero: '123',
    complemento: 'Condomínio',
    bairro: 'Jardim Botânico',
    cidade: 'São Paulo',
    estado: 'SP',
    cep: '01234-567',
  },
  quantidadeMoradores: 150,
  quantidadeApartamentos: 120,
  telefoneContato: '(11) 3456-7890',
  contatoPortaria: '(11) 3456-7891',
  sindico: {
    id: '1',
    nome: 'João Silva',
    telefone: '(11) 98765-4321',
    email: 'joao.silva@email.com',
    apartamento: '101',
    dataInicio: new Date('2023-01-01'),
    ativo: true,
  },
  subSindico: {
    id: '2',
    nome: 'Maria Santos',
    telefone: '(11) 98765-4322',
    email: 'maria.santos@email.com',
    apartamento: '205',
    dataInicio: new Date('2023-01-01'),
    ativo: true,
  },
  zelador: {
    id: '3',
    nome: 'Pedro Oliveira',
    telefone: '(11) 98765-4323',
    email: 'pedro.oliveira@email.com',
    dataInicio: new Date('2022-06-01'),
    ativo: true,
  },
  funcionarios: [],
  empresasTerceirizadas: [],
  fornecedores: [],
  moradores: [],
  veiculos: [],
  visitantes: [],
  veiculosVisitantes: [],
  reservas: [],
  informacoesColeta: {
    id: '1',
    tipo: 'organico',
    diaSemana: 'Segunda-feira',
    horario: '08:00',
    observacoes: 'Coleta de lixo orgânico',
    ativo: true,
  },
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const mockMoradores: Morador[] = [
  {
    id: '1',
    nome: 'Ana Costa',
    apartamento: '101',
    endereco: {
      logradouro: 'Rua das Flores',
      numero: '123',
      complemento: 'Apto 101',
      bairro: 'Jardim Botânico',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01234-567',
    },
    email: 'ana.costa@email.com',
    telefone: '(11) 98765-4321',
    usuario: 'ana.costa',
    senha: 'senha123',
    proprietario: true,
    dataEntrada: new Date('2020-01-01'),
    ativo: true,
  },
  {
    id: '2',
    nome: 'Carlos Ferreira',
    apartamento: '205',
    endereco: {
      logradouro: 'Rua das Flores',
      numero: '123',
      complemento: 'Apto 205',
      bairro: 'Jardim Botânico',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01234-567',
    },
    email: 'carlos.ferreira@email.com',
    telefone: '(11) 98765-4322',
    usuario: 'carlos.ferreira',
    senha: 'senha123',
    proprietario: false,
    dataEntrada: new Date('2021-03-15'),
    ativo: true,
  },
];

export const mockFuncionarios: Funcionario[] = [
  {
    id: '1',
    nome: 'Roberto Lima',
    rg: '12.345.678-9',
    cpf: '123.456.789-00',
    telefonePessoal: '(11) 98765-4324',
    telefoneProfissional: '(11) 3456-7892',
    emailPessoal: 'roberto.lima@email.com',
    emailProfissional: 'roberto.lima@empresa.com',
    cargo: 'Porteiro',
    empresa: 'Segurança Total Ltda',
    dataAdmissao: new Date('2022-01-01'),
    ativo: true,
  },
  {
    id: '2',
    nome: 'Fernanda Alves',
    rg: '98.765.432-1',
    cpf: '987.654.321-00',
    telefonePessoal: '(11) 98765-4325',
    telefoneProfissional: '(11) 3456-7893',
    emailPessoal: 'fernanda.alves@email.com',
    emailProfissional: 'fernanda.alves@limpeza.com',
    cargo: 'Auxiliar de Limpeza',
    empresa: 'Limpeza Express Ltda',
    dataAdmissao: new Date('2022-02-01'),
    ativo: true,
  },
];

export const mockEmpresasTerceirizadas: EmpresaTerceirizada[] = [
  {
    id: '1',
    nome: 'Segurança Total Ltda',
    cnpj: '98.765.432/0001-10',
    tipo: 'seguranca',
    endereco: {
      logradouro: 'Rua da Segurança',
      numero: '456',
      complemento: 'Sala 101',
      bairro: 'Centro',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01234-890',
    },
    telefone: '(11) 3456-7894',
    email: 'contato@segurancatotal.com',
    responsavel: 'Marcos Silva',
    funcionarios: [],
    contratoInicio: new Date('2022-01-01'),
    contratoFim: new Date('2024-12-31'),
    ativo: true,
  },
  {
    id: '2',
    nome: 'Limpeza Express Ltda',
    cnpj: '11.222.333/0001-44',
    tipo: 'limpeza',
    endereco: {
      logradouro: 'Rua da Limpeza',
      numero: '789',
      complemento: 'Sala 202',
      bairro: 'Vila Madalena',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01234-567',
    },
    telefone: '(11) 3456-7895',
    email: 'contato@limpezaexpress.com',
    responsavel: 'Lucia Santos',
    funcionarios: [],
    contratoInicio: new Date('2022-02-01'),
    contratoFim: new Date('2024-12-31'),
    ativo: true,
  },
];

export const mockFornecedores: Fornecedor[] = [
  {
    id: '1',
    nome: 'Materiais de Construção Silva',
    cnpj: '22.333.444/0001-55',
    tipo: 'construcao',
    endereco: {
      logradouro: 'Rua dos Materiais',
      numero: '321',
      complemento: 'Galpão 1',
      bairro: 'Vila Industrial',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01234-789',
    },
    telefone: '(11) 3456-7896',
    email: 'contato@materiaissilva.com',
    responsavel: 'Antonio Silva',
    produtos: ['Cimento', 'Areia', 'Tijolos', 'Tintas'],
    ativo: true,
  },
  {
    id: '2',
    nome: 'Produtos de Limpeza Clean',
    cnpj: '33.444.555/0001-66',
    tipo: 'limpeza',
    endereco: {
      logradouro: 'Rua da Limpeza',
      numero: '654',
      complemento: 'Depósito',
      bairro: 'Vila Limpa',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01234-890',
    },
    telefone: '(11) 3456-7897',
    email: 'contato@produtosclean.com',
    responsavel: 'Beatriz Costa',
    produtos: ['Detergente', 'Desinfetante', 'Papel Higiênico', 'Sabão'],
    ativo: true,
  },
];

export const mockVeiculos: Veiculo[] = [
  {
    id: '1',
    placa: 'ABC-1234',
    modelo: 'Civic',
    marca: 'Honda',
    cor: 'Prata',
    ano: 2020,
    proprietarioId: '1',
    proprietarioNome: 'Ana Costa',
    apartamento: '101',
    tipo: 'carro',
    ativo: true,
  },
  {
    id: '2',
    placa: 'XYZ-5678',
    modelo: 'CG 150',
    marca: 'Honda',
    cor: 'Vermelha',
    ano: 2021,
    proprietarioId: '2',
    proprietarioNome: 'Carlos Ferreira',
    apartamento: '205',
    tipo: 'moto',
    ativo: true,
  },
];

export const mockVisitantes: Visitante[] = [
  {
    id: '1',
    nome: 'Paulo Mendes',
    documento: '123.456.789-00',
    telefone: '(11) 98765-4326',
    apartamentoVisitado: '101',
    moradorResponsavel: 'Ana Costa',
    dataEntrada: new Date('2024-01-15T10:00:00'),
    dataSaida: new Date('2024-01-15T12:00:00'),
    motivo: 'Visita familiar',
    autorizado: true,
  },
  {
    id: '2',
    nome: 'Juliana Lima',
    documento: '987.654.321-00',
    telefone: '(11) 98765-4327',
    apartamentoVisitado: '205',
    moradorResponsavel: 'Carlos Ferreira',
    dataEntrada: new Date('2024-01-15T14:00:00'),
    motivo: 'Entrega de encomenda',
    autorizado: true,
  },
];

export const mockReservas: Reserva[] = [
  {
    id: '1',
    tipo: 'churrasqueira',
    moradorId: '1',
    moradorNome: 'Ana Costa',
    apartamento: '101',
    dataInicio: new Date('2024-01-20T18:00:00'),
    dataFim: new Date('2024-01-20T22:00:00'),
    quantidadePessoas: 8,
    observacoes: 'Aniversário da filha',
    status: 'aprovada',
    valor: 50,
  },
  {
    id: '2',
    tipo: 'salao',
    moradorId: '2',
    moradorNome: 'Carlos Ferreira',
    apartamento: '205',
    dataInicio: new Date('2024-01-25T19:00:00'),
    dataFim: new Date('2024-01-25T23:00:00'),
    quantidadePessoas: 15,
    observacoes: 'Reunião de trabalho',
    status: 'pendente',
    valor: 100,
  },
];

export const mockOcorrencias: Ocorrencia[] = [
  {
    id: '1',
    tipo: 'manutencao',
    titulo: 'Vazamento no apartamento 101',
    descricao: 'Vazamento na pia da cozinha',
    moradorId: '1',
    moradorNome: 'Ana Costa',
    apartamento: '101',
    prioridade: 'alta',
    status: 'em_andamento',
    dataAbertura: new Date('2024-01-14T08:00:00'),
    responsavel: 'Pedro Oliveira',
    observacoes: 'Técnico agendado para amanhã',
  },
  {
    id: '2',
    tipo: 'seguranca',
    titulo: 'Pessoa suspeita no estacionamento',
    descricao: 'Homem não identificado circulando no estacionamento',
    prioridade: 'urgente',
    status: 'aberta',
    dataAbertura: new Date('2024-01-15T22:00:00'),
    responsavel: 'Roberto Lima',
    observacoes: 'Vigilância reforçada',
  },
];

export const mockUsuarios: Usuario[] = [
  {
    id: '1',
    nome: 'Administrador',
    email: 'admin@condominio.com',
    senha: 'admin123',
    tipo: 'admin',
    ativo: true,
    ultimoAcesso: new Date(),
  },
  {
    id: '2',
    nome: 'João Silva',
    email: 'joao.silva@email.com',
    senha: 'sindico123',
    tipo: 'sindico',
    ativo: true,
    ultimoAcesso: new Date(),
  },
]; 